#! /bin/sh

if [ -z $1 ]; then
    echo usage: $0 filename.svg
    exit 1
fi

if [ ! -f $1 ]; then
    echo error: file "$1" is missing
    exit 1
fi

ifile=$1
ofile=$(basename $1 .svg).png
b64=$ofile.b64

inkscape -f $1 -w 250 -h 250 -e $ofile

echo '<IMG ALT="TEXT TITLE HERE" SRC="data:image/png;base64,' > $b64
base64 $ofile >> $b64
echo '">' >> $b64

rm $ofile
